using Nodlyn.Core.Connectors;

namespace Nodlyn.CustomComponent;

/// <summary>
/// Connector definition for the Nodlyn Custom Component plugin.
///
/// This class registers the plugin with the Nodlyn platform and declares
/// all the capabilities (workflow nodes) that the plugin provides.
///
/// HOW IT WORKS:
///   1. The Nodlyn platform scans the plugins/custom/ directory at startup.
///   2. It finds this class (which extends DeviceConnectorDefinition) and
///      registers it alongside built-in connectors.
///   3. The capabilities listed here appear as draggable blocks in the
///      workflow editor under the "Custom" section.
///   4. Each capability has a matching executor class that runs the logic.
///
/// TO ADD A NEW NODE:
///   1. Add a new CapabilityContract to the Capabilities list below.
///   2. Create a matching executor class that extends CapabilityExecutor
///      with the same ConnectorId and CapabilityId.
///   3. Rebuild and copy the DLL to plugins/custom/.
///
/// NAMING CONVENTION:
///   - ConnectorId:  "custom.yourname"   (dot-separated, lowercase)
///   - CapabilityId: "doSomething"       (camelCase, descriptive verb)
///   - NodeType:     "{ConnectorId}.{CapabilityId}" (auto-generated by the platform)
/// </summary>
public class CustomConnectorDefinition : DeviceConnectorDefinition
{
    // ───────────────────────────────────────────────────────────────────────
    // CONNECTOR IDENTITY
    // These properties identify your plugin in the Nodlyn platform.
    // ConnectorId must be globally unique across all plugins.
    // ───────────────────────────────────────────────────────────────────────

    public override string ConnectorId  => "custom.example";
    public override string DisplayName  => "Example Plugin";
    public override string Icon         => "🧩";
    public override string Color        => "#8b5cf6";  // violet
    public override string Description  => "An example custom component plugin for the Nodlyn platform. "
                                         + "Use this as a starting point for building your own plugins.";

    // ───────────────────────────────────────────────────────────────────────
    // CAPABILITIES
    // Each capability becomes a workflow node that users can drag onto
    // the canvas. The CapabilityId must match the executor's CapabilityId.
    // ───────────────────────────────────────────────────────────────────────

    public override IReadOnlyList<CapabilityContract> Capabilities =>
    [
        // ── Hello World: a minimal action node ──────────────────────────
        new()
        {
            CapabilityId   = "helloWorld",
            DisplayName    = "Hello World",
            Icon           = "👋",
            Color          = "#8b5cf6",
            Category       = "action",
            Description    = "A simple action node that greets the user. "
                           + "Demonstrates the basic structure of a custom plugin executor.",

            CapabilityType = CapabilityType.Action,
            SecurityLevel  = SecurityLevel.Safe,
            HasInput       = true,
            HasOutput      = true,
            IsSideEffectFree = true,

            // Settings appear as form fields in the node inspector panel.
            Settings =
            [
                new()
                {
                    Name         = "name",
                    Label        = "Your Name",
                    Type         = "text",
                    DefaultValue = "World",
                    Placeholder  = "Enter a name to greet",
                    Required     = true,
                },
                new()
                {
                    Name         = "greeting",
                    Label        = "Greeting Style",
                    Type         = "select",
                    DefaultValue = "friendly",
                    Options =
                    [
                        new() { Value = "friendly", Label = "Friendly (Hello!)" },
                        new() { Value = "formal",   Label = "Formal (Good day)" },
                        new() { Value = "casual",   Label = "Casual (Hey!)" },
                    ],
                },
                new()
                {
                    Name         = "includeTimestamp",
                    Label        = "Include Timestamp",
                    Type         = "toggle",
                    DefaultValue = "true",
                },
            ],

            // OutputsSchema documents what the node produces.
            // These values are available to downstream nodes in the workflow.
            OutputsSchema = new Dictionary<string, object>
            {
                ["message"]   = "string — the greeting message",
                ["greetedAt"] = "string — ISO-8601 timestamp (if includeTimestamp is enabled)",
            },
        },

        // ── Text Transform: demonstrates pipeline data processing ───────
        new()
        {
            CapabilityId   = "textTransform",
            DisplayName    = "Text Transform",
            Icon           = "✏️",
            Color          = "#06b6d4",  // cyan
            Category       = "action",
            Description    = "Transforms text from the pipeline input by applying "
                           + "operations like uppercase, lowercase, reverse, or trim. "
                           + "Demonstrates how to read pipeline input and pass data downstream.",

            CapabilityType = CapabilityType.Transform,
            SecurityLevel  = SecurityLevel.Safe,
            HasInput       = true,
            HasOutput      = true,
            IsSideEffectFree = true,

            Settings =
            [
                new()
                {
                    Name         = "inputField",
                    Label        = "Input Field",
                    Type         = "text",
                    DefaultValue = "message",
                    Placeholder  = "Field name from pipeline input",
                },
                new()
                {
                    Name         = "operation",
                    Label        = "Operation",
                    Type         = "select",
                    DefaultValue = "uppercase",
                    Required     = true,
                    Options =
                    [
                        new() { Value = "uppercase", Label = "UPPERCASE" },
                        new() { Value = "lowercase", Label = "lowercase" },
                        new() { Value = "reverse",   Label = "esreveR" },
                        new() { Value = "trim",      Label = "Trim whitespace" },
                        new() { Value = "length",    Label = "String length" },
                    ],
                },
            ],

            OutputsSchema = new Dictionary<string, object>
            {
                ["result"]    = "string — the transformed text (or integer for 'length')",
                ["operation"] = "string — which operation was applied",
                ["original"]  = "string — the original input text",
            },
        },

        // ── Number Check: demonstrates a condition node ─────────────────
        new()
        {
            CapabilityId   = "numberCheck",
            DisplayName    = "Number Check",
            Icon           = "🔢",
            Color          = "#f59e0b",  // amber
            Category       = "condition",
            Description    = "Evaluates a numeric value from the pipeline against a threshold. "
                           + "Outputs true/false to control conditional workflow branches. "
                           + "Demonstrates how to build a condition node.",

            CapabilityType = CapabilityType.Condition,
            SecurityLevel  = SecurityLevel.Safe,
            HasInput       = true,
            HasOutput      = true,
            IsSideEffectFree = true,
            OutputBranches = 2,  // true / false branches

            Settings =
            [
                new()
                {
                    Name         = "inputField",
                    Label        = "Input Field",
                    Type         = "text",
                    DefaultValue = "value",
                    Placeholder  = "Field name containing the number",
                },
                new()
                {
                    Name         = "operator",
                    Label        = "Comparison",
                    Type         = "select",
                    DefaultValue = "greaterThan",
                    Required     = true,
                    Options =
                    [
                        new() { Value = "greaterThan",    Label = "> Greater than" },
                        new() { Value = "lessThan",       Label = "< Less than" },
                        new() { Value = "equals",         Label = "= Equals" },
                        new() { Value = "greaterOrEqual", Label = ">= Greater or equal" },
                        new() { Value = "lessOrEqual",    Label = "<= Less or equal" },
                    ],
                },
                new()
                {
                    Name         = "threshold",
                    Label        = "Threshold",
                    Type         = "number",
                    DefaultValue = "0",
                    Required     = true,
                },
            ],

            OutputsSchema = new Dictionary<string, object>
            {
                ["result"]    = "boolean — whether the condition is true",
                ["value"]     = "number — the evaluated value",
                ["threshold"] = "number — the comparison threshold",
                ["operator"]  = "string — the comparison operator used",
            },
        },
    ];
}
